package bandcamp

// Unused; kept only for reference. this is the result of html scraping
// off of a tralbum download page.
type digitalItem struct {
	RecaptchaPublicKey          string `json:"recaptcha_public_key"`
	InvisibleRecaptchaPublicKey string `json:"invisible_recaptcha_public_key"`
	LocalizePage                bool   `json:"localize_page"`
	Locale                      string `json:"locale"`
	Languages                   struct {
		En string `json:"en"`
		De string `json:"de"`
		Es string `json:"es"`
		Fr string `json:"fr"`
		Pt string `json:"pt"`
		Ja string `json:"ja"`
	} `json:"languages"`
	HelpCenterURL string `json:"help_center_url"`
	Templglobals  struct {
		EndpointMobilized bool `json:"endpoint_mobilized"`
		IsPhone           bool `json:"is_phone"`
	} `json:"templglobals"`
	Cfg struct {
		StatDlJSON                          bool `json:"stat_dl_json"`
		MobileApp                           bool `json:"mobile_app"`
		Gifting                             bool `json:"gifting"`
		OpenSignup                          bool `json:"open_signup"`
		MenubarAutocompleteEnabled          bool `json:"menubar_autocomplete_enabled"`
		UseElasticsearchBackedSearch        bool `json:"use_elasticsearch_backed_search"`
		NewSearchAPIService                 bool `json:"new_search_api_service"`
		SearchTracking                      bool `json:"search_tracking"`
		SingleSignUp                        bool `json:"single_sign_up"`
		FanSignupUseCaptcha                 bool `json:"fan_signup_use_captcha"`
		GiftCards                           bool `json:"gift_cards"`
		OrderHistory                        bool `json:"order_history"`
		HeaderRework2018                    bool `json:"header_rework_2018"`
		SearchDiscoveryOneFilterDesktopOnly bool `json:"search_discovery_one_filter_desktop_only"`
		SearchDiscoveryOneFilterRollout     bool `json:"search_discovery_one_filter_rollout"`
		Community                           bool `json:"community"`
		LoginUseCaptcha                     bool `json:"login_use_captcha"`
	} `json:"cfg"`
	Identities struct {
		User struct {
			ID int `json:"id"`
		} `json:"user"`
		IPCountryCode any `json:"ip_country_code"`
		Fan           struct {
			ID       int    `json:"id"`
			Username string `json:"username"`
			Name     string `json:"name"`
			Photo    int    `json:"photo"`
			Private  bool   `json:"private"`
			Verified bool   `json:"verified"`
			URL      string `json:"url"`
		} `json:"fan"`
		IsPageBandMember     any   `json:"is_page_band_member"`
		SubscribedToPageBand any   `json:"subscribed_to_page_band"`
		Bands                []any `json:"bands"`
		Partner              bool  `json:"partner"`
		IsAdmin              bool  `json:"is_admin"`
		Labels               []any `json:"labels"`
	} `json:"identities"`
	DigitalItems []struct {
		SaleID                      int     `json:"sale_id"`
		ItemType                    string  `json:"item_type"`
		ItemID                      int     `json:"item_id"`
		SaleReleaseDate             any     `json:"sale_release_date"`
		Quantity                    int     `json:"quantity"`
		UnitPrice                   float64 `json:"unit_price"`
		Currency                    string  `json:"currency"`
		SoldDate                    string  `json:"sold_date"`
		DownloadType                string  `json:"download_type"`
		DownloadID                  int     `json:"download_id"`
		SaleItemState               string  `json:"sale_item_state"`
		BandID                      int64   `json:"band_id"`
		BandName                    string  `json:"band_name"`
		GenreID                     int     `json:"genre_id"`
		BandEnabled                 int     `json:"band_enabled"`
		HasEnhancedSeller           int     `json:"has_enhanced_seller"`
		PaymentID                   int64   `json:"payment_id"`
		PaymentType                 string  `json:"payment_type"`
		BuyerType                   string  `json:"buyer_type"`
		BuyerID                     int     `json:"buyer_id"`
		PaymentEmail                string  `json:"payment_email"`
		FulfillmentDays             any     `json:"fulfillment_days"`
		PackageTitle                any     `json:"package_title"`
		PackageTypeID               any     `json:"package_type_id"`
		OptionsTitle                any     `json:"options_title"`
		IsLiveTicket                any     `json:"is_live_ticket"`
		LiveEventID                 any     `json:"live_event_id"`
		LiveEventTitle              any     `json:"live_event_title"`
		LiveEventDescription        any     `json:"live_event_description"`
		LiveEventScheduledStartDate any     `json:"live_event_scheduled_start_date"`
		LiveEventScheduledEndDate   any     `json:"live_event_scheduled_end_date"`
		LiveEventEndDate            any     `json:"live_event_end_date"`
		LiveEventTimezoneSymID      any     `json:"live_event_timezone_sym_id"`
		ServiceType                 any     `json:"service_type"`
		Shippable                   any     `json:"shippable"`
		MarkedShippedDate           any     `json:"marked_shipped_date"`
		LicenseID                   any     `json:"license_id"`
		OptionName                  any     `json:"option_name"`
		PackageSubdomain            string  `json:"package_subdomain"`
		PackageCustomDomain         any     `json:"package_custom_domain"`
		PackageCustomDomainVerified any     `json:"package_custom_domain_verified"`
		PackageSlugText             any     `json:"package_slug_text"`
		PackageSlugType             any     `json:"package_slug_type"`
		ArtID                       int     `json:"art_id"`
		PackageImageID              any     `json:"package_image_id"`
		ReleaseDate                 string  `json:"release_date"`
		PackageReleaseDate          string  `json:"package_release_date"`
		TralbumID                   int     `json:"tralbum_id"`
		DownloadPref                int     `json:"download_pref"`
		Killed                      any     `json:"killed"`
		GiftSenderNote              any     `json:"gift_sender_note"`
		GiftState                   any     `json:"gift_state"`
		GiftRedeemedDate            any     `json:"gift_redeemed_date"`
		GiftRecipientEmailHidden    any     `json:"gift_recipient_email_hidden"`
		GiftRecipientEmail          any     `json:"gift_recipient_email"`
		GiftSenderName              any     `json:"gift_sender_name"`
		GiftRecipientName           any     `json:"gift_recipient_name"`
		GiftCardValue               any     `json:"gift_card_value"`
		GiftCardArtID               any     `json:"gift_card_art_id"`
		GiftCardCurrency            any     `json:"gift_card_currency"`
		GiftCardRecipientEmail      any     `json:"gift_card_recipient_email"`
		LabelMailingListAddress     any     `json:"label_mailing_list_address"`
		LabelMailingListUnsubscribe any     `json:"label_mailing_list_unsubscribe"`
		SubscriberOnly              any     `json:"subscriber_only"`
		TaxSystem                   any     `json:"tax_system"`
		Type                        string  `json:"type"`
		IsPreorder                  any     `json:"is_preorder"`
		PackageTypeName             any     `json:"package_type_name"`
		IncludesDigital             bool    `json:"includes_digital"`
		NodlDesc                    any     `json:"nodl_desc"`
		Desc                        string  `json:"desc"`
		Title                       string  `json:"title"`
		TrackCount                  int     `json:"track_count"`
		DescTrackCount              int     `json:"desc_track_count"`
		Artist                      string  `json:"artist"`
		URLHints                    struct {
			Subdomain            string `json:"subdomain"`
			CustomDomain         any    `json:"custom_domain"`
			CustomDomainVerified any    `json:"custom_domain_verified"`
			Slug                 string `json:"slug"`
			ItemType             string `json:"item_type"`
		} `json:"url_hints"`
		PageURL    string `json:"page_url"`
		GiftLink   string `json:"gift_link"`
		ThumbTitle string `json:"thumb_title"`
		PaymentAmt string `json:"payment_amt"`
		Shareable  bool   `json:"shareable"`
		Downloads  struct {
			Mp3V0 struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"mp3-v0"`
			Mp3320 struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"mp3-320"`
			Flac struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"flac"`
			AacHi struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"aac-hi"`
			Vorbis struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"vorbis"`
			Alac struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"alac"`
			Wav struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"wav"`
			AiffLossless struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"aiff-lossless"`
		} `json:"downloads"`
		Ready           bool    `json:"ready"`
		NotifyMe        bool    `json:"notify_me"`
		NotifyMeLabel   bool    `json:"notify_me_label"`
		MinPrice        float64 `json:"min_price"`
		IsPureFree      bool    `json:"is_pure_free"`
		DownloadTypeStr string  `json:"download_type_str"`
		PaidFor         bool    `json:"paid_for"`
		IsNameYourPrice bool    `json:"is_name_your_price"`
	} `json:"digital_items"`
	FanEmail        string `json:"fan_email"`
	Packages        []any  `json:"packages"`
	LiveTickets     []any  `json:"live_tickets"`
	SentGifts       []any  `json:"sent_gifts"`
	DownloadFormats []struct {
		Name          string `json:"name"`
		DbColumn      string `json:"db_column"`
		FileExtension string `json:"file_extension"`
		MimeType      string `json:"mime_type"`
		Description   string `json:"description"`
		HasVariants   bool   `json:"has_variants,omitempty"`
	} `json:"download_formats"`
	DownloadFormat     string `json:"download_format"`
	Multidownload      bool   `json:"multidownload"`
	GiftDownloadPage   bool   `json:"gift_download_page"`
	LoggedOutFan       bool   `json:"logged_out_fan"`
	AppTralbumURL      string `json:"app_tralbum_url"`
	DownloadDifficulty string `json:"download_difficulty"`
	Platform           string `json:"platform"`
	IsRedownload       bool   `json:"is_redownload"`
	HasDownloads       bool   `json:"has_downloads"`
	DownloadItems      []struct {
		SaleID                      int     `json:"sale_id"`
		ItemType                    string  `json:"item_type"`
		ItemID                      int     `json:"item_id"`
		SaleReleaseDate             any     `json:"sale_release_date"`
		Quantity                    int     `json:"quantity"`
		UnitPrice                   float64 `json:"unit_price"`
		Currency                    string  `json:"currency"`
		SoldDate                    string  `json:"sold_date"`
		DownloadType                string  `json:"download_type"`
		DownloadID                  int     `json:"download_id"`
		SaleItemState               string  `json:"sale_item_state"`
		BandID                      int64   `json:"band_id"`
		BandName                    string  `json:"band_name"`
		GenreID                     int     `json:"genre_id"`
		BandEnabled                 int     `json:"band_enabled"`
		HasEnhancedSeller           int     `json:"has_enhanced_seller"`
		PaymentID                   int64   `json:"payment_id"`
		PaymentType                 string  `json:"payment_type"`
		BuyerType                   string  `json:"buyer_type"`
		BuyerID                     int     `json:"buyer_id"`
		PaymentEmail                string  `json:"payment_email"`
		FulfillmentDays             any     `json:"fulfillment_days"`
		PackageTitle                any     `json:"package_title"`
		PackageTypeID               any     `json:"package_type_id"`
		OptionsTitle                any     `json:"options_title"`
		IsLiveTicket                any     `json:"is_live_ticket"`
		LiveEventID                 any     `json:"live_event_id"`
		LiveEventTitle              any     `json:"live_event_title"`
		LiveEventDescription        any     `json:"live_event_description"`
		LiveEventScheduledStartDate any     `json:"live_event_scheduled_start_date"`
		LiveEventScheduledEndDate   any     `json:"live_event_scheduled_end_date"`
		LiveEventEndDate            any     `json:"live_event_end_date"`
		LiveEventTimezoneSymID      any     `json:"live_event_timezone_sym_id"`
		ServiceType                 any     `json:"service_type"`
		Shippable                   any     `json:"shippable"`
		MarkedShippedDate           any     `json:"marked_shipped_date"`
		LicenseID                   any     `json:"license_id"`
		OptionName                  any     `json:"option_name"`
		PackageSubdomain            string  `json:"package_subdomain"`
		PackageCustomDomain         any     `json:"package_custom_domain"`
		PackageCustomDomainVerified any     `json:"package_custom_domain_verified"`
		PackageSlugText             any     `json:"package_slug_text"`
		PackageSlugType             any     `json:"package_slug_type"`
		ArtID                       int     `json:"art_id"`
		PackageImageID              any     `json:"package_image_id"`
		ReleaseDate                 string  `json:"release_date"`
		PackageReleaseDate          string  `json:"package_release_date"`
		TralbumID                   int     `json:"tralbum_id"`
		DownloadPref                int     `json:"download_pref"`
		Killed                      any     `json:"killed"`
		GiftSenderNote              any     `json:"gift_sender_note"`
		GiftState                   any     `json:"gift_state"`
		GiftRedeemedDate            any     `json:"gift_redeemed_date"`
		GiftRecipientEmailHidden    any     `json:"gift_recipient_email_hidden"`
		GiftRecipientEmail          any     `json:"gift_recipient_email"`
		GiftSenderName              any     `json:"gift_sender_name"`
		GiftRecipientName           any     `json:"gift_recipient_name"`
		GiftCardValue               any     `json:"gift_card_value"`
		GiftCardArtID               any     `json:"gift_card_art_id"`
		GiftCardCurrency            any     `json:"gift_card_currency"`
		GiftCardRecipientEmail      any     `json:"gift_card_recipient_email"`
		LabelMailingListAddress     any     `json:"label_mailing_list_address"`
		LabelMailingListUnsubscribe any     `json:"label_mailing_list_unsubscribe"`
		SubscriberOnly              any     `json:"subscriber_only"`
		TaxSystem                   any     `json:"tax_system"`
		Type                        string  `json:"type"`
		IsPreorder                  any     `json:"is_preorder"`
		PackageTypeName             any     `json:"package_type_name"`
		IncludesDigital             bool    `json:"includes_digital"`
		NodlDesc                    any     `json:"nodl_desc"`
		Desc                        string  `json:"desc"`
		Title                       string  `json:"title"`
		TrackCount                  int     `json:"track_count"`
		DescTrackCount              int     `json:"desc_track_count"`
		Artist                      string  `json:"artist"`
		URLHints                    struct {
			Subdomain            string `json:"subdomain"`
			CustomDomain         any    `json:"custom_domain"`
			CustomDomainVerified any    `json:"custom_domain_verified"`
			Slug                 string `json:"slug"`
			ItemType             string `json:"item_type"`
		} `json:"url_hints"`
		PageURL    string `json:"page_url"`
		GiftLink   string `json:"gift_link"`
		ThumbTitle string `json:"thumb_title"`
		PaymentAmt string `json:"payment_amt"`
		Shareable  bool   `json:"shareable"`
		Downloads  struct {
			Mp3V0 struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"mp3-v0"`
			Mp3320 struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"mp3-320"`
			Flac struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"flac"`
			AacHi struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"aac-hi"`
			Vorbis struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"vorbis"`
			Alac struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"alac"`
			Wav struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"wav"`
			AiffLossless struct {
				SizeMb       string `json:"size_mb"`
				Description  string `json:"description"`
				EncodingName string `json:"encoding_name"`
				URL          string `json:"url"`
			} `json:"aiff-lossless"`
		} `json:"downloads"`
		Ready           bool    `json:"ready"`
		NotifyMe        bool    `json:"notify_me"`
		NotifyMeLabel   bool    `json:"notify_me_label"`
		MinPrice        float64 `json:"min_price"`
		IsPureFree      bool    `json:"is_pure_free"`
		DownloadTypeStr string  `json:"download_type_str"`
		PaidFor         bool    `json:"paid_for"`
		IsNameYourPrice bool    `json:"is_name_your_price"`
	} `json:"download_items"`
	CancelPledgeInfo any `json:"cancel_pledge_info"`
	SignupParams     struct {
	} `json:"signup_params"`
	FanOnboarding struct {
		Tooltips                 any    `json:"tooltips"`
		NumTooltips              int    `json:"num_tooltips"`
		TooltipNumber            any    `json:"tooltip_number"`
		CurrentIndex             any    `json:"current_index"`
		Complete                 bool   `json:"complete"`
		ShowCollectionBanner     bool   `json:"show_collection_banner"`
		ShowFeedBanner           bool   `json:"show_feed_banner"`
		ShowVerifyBanner         bool   `json:"show_verify_banner"`
		FirstWishlistedItemTitle any    `json:"first_wishlisted_item_title"`
		FirstWishlistedItemType  any    `json:"first_wishlisted_item_type"`
		FirstPurchasedItemTitle  any    `json:"first_purchased_item_title"`
		FirstPurchasedItemType   any    `json:"first_purchased_item_type"`
		Template                 any    `json:"template"`
		Email                    string `json:"email"`
		HasCollection            int    `json:"has_collection"`
		HasSeenTooltips          bool   `json:"has_seen_tooltips"`
		ShowFirstWishlistTooltip bool   `json:"show_first_wishlist_tooltip"`
		Deferred                 bool   `json:"deferred"`
	} `json:"fan_onboarding"`
}
